name: recipe_app
description: A Social Recipe Application .

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  provider: ^6.0.0
  flutter_colorpicker: ^0.6.0
  intl: ^0.17.0
  uuid: ^3.0.4


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/profile_pics/
    - assets/fooderlich_assets/
    - assets/sample_data/

